# Generated by Django 3.0 on 2020-09-05 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webburguer_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pago', models.BooleanField()),
                ('franqueada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webburguer_app.Franqueada')),
            ],
        ),
        migrations.RemoveField(
            model_name='franquia',
            name='tipo',
        ),
        migrations.CreateModel(
            name='PedidoProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webburguer_app.Pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webburguer_app.Produto')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='produtos',
            field=models.ManyToManyField(through='webburguer_app.PedidoProduto', to='webburguer_app.Produto'),
        ),
    ]
