# Generated by Django 3.1.1 on 2020-09-09 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webburguer_app', '0002_auto_20200905_1541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='burgueruser',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AlterModelOptions(
            name='pedidoproduto',
            options={'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterField(
            model_name='burgueruser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
