# Generated by Django 3.0 on 2020-09-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webburguer_app', '0003_auto_20200909_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burgueruser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
    ]
