# Generated by Django 3.1.1 on 2020-09-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webburguer_app', '0004_auto_20200915_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='pago',
            field=models.BooleanField(null=True),
        ),
    ]
