# Generated by Django 3.1.1 on 2020-09-15 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webburguer_app', '0005_auto_20200915_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='produtos',
            field=models.ManyToManyField(null=True, through='webburguer_app.PedidoProduto', to='webburguer_app.Produto'),
        ),
    ]
