# Generated by Django 3.1.1 on 2020-09-16 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webburguer_app', '0007_auto_20200915_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='produtos',
        ),
        migrations.AddField(
            model_name='pedido',
            name='produto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webburguer_app.produto'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='quantidade',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='PedidoProduto',
        ),
    ]
