# Generated by Django 3.1.1 on 2020-09-16 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webburguer_app', '0008_auto_20200915_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='franqueada',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webburguer_app.franqueada'),
        ),
    ]
