# Generated by Django 3.1.1 on 2020-09-16 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webburguer_app', '0009_auto_20200915_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='descricao',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='franqueada',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webburguer_app.franqueada'),
        ),
    ]
