# Generated by Django 3.1.1 on 2020-09-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webburguer_app', '0011_produto_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.FloatField(null=True),
        ),
    ]
