# Generated by Django 3.1.1 on 2020-09-16 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webburguer_app', '0012_auto_20200916_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='valor',
            field=models.FloatField(max_length=100),
        ),
    ]
